name: CI with Cache

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Create the pip cache directory before caching
      - name: Prepare cache directory
        run: mkdir -p ~/.cache/pip

      # Cache step with ID "cache"
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-3c555b8

      # ✅ Step explicitly named "prime-cache-3c555b8"
      - name: prime-cache-3c555b8
        run: echo "Cache result: ${{ steps.cache.outputs.cache-hit }}"

      # Example install step
      - name: Install dependencies
        run: pip install fastapi numpy
